### ISSUE TITLE
JDK-8209180: Media fails to load source from custom image, with jrt: URL

### ISSUE THREAD

**Issue by wuhongzhi** [javafxports/openjdk-jfx#251]
java.lang.UnsupportedOperationException: Unsupported protocol "jrt"
	at javafx.media/com.sun.media.jfxmedia.locator.Locator.<init>(Locator.java:240)
	at javafx.media/javafx.scene.media.Media.<init>(Media.java:393)
	at JWeb/com.chrisnewland.demofx.effect.video.VideoStream.<init>(VideoStream.java:31)
	at JWeb/com.chrisnewland.demofx.effect.video.RawPlayer.init(RawPlayer.java:25)
	at JWeb/com.chrisnewland.demofx.effect.video.RawPlayer.<init>(RawPlayer.java:21)
	at JWeb/com.chrisnewland.demofx.effect.effectfactory.DemoFX3ScriptFactory.videoCubeAndMandalas(DemoFX3ScriptFactory.java:270)
	at JWeb/com.chrisnewland.demofx.effect.effectfactory.DemoFX3ScriptFactory.space(DemoFX3ScriptFactory.java:168)
	at JWeb/com.chrisnewland.demofx.effect.effectfactory.DemoFX3ScriptFactory.getEffects(DemoFX3ScriptFactory.java:111)
	at JWeb/com.chrisnewland.demofx.DemoFX.getScene(DemoFX.java:123)
	at JWeb/com.chrisnewland.demofx.DemoFXApplication.start(DemoFXApplication.java:32)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kevinrushforth** [comment]
This is already tracked here: [JDK-8209180](https://bugs.openjdk.java.net/browse/JDK-8209180)
