### ISSUE TITLE
Window order is not correct when Modality.WINDOW_MODAL (openjfx 11.0.2)

### ISSUE THREAD

**Issue by tsayao** [javafxports/openjdk-jfx#377]
**Issue**
When managing multiple windows on our OpenJfx application sometimes a window that was first opened pops on the front of a current window. It happens when there is a modal window.

We are always sure to initOwner() with the parent window and then set       initModality(Modality.WINDOW_MODAL).

**Tested platforms:**
Xubuntu 18.04
Ubuntu 18.04
Ubuntu 18.10
(seems not to be a window manager issue)

**To Reproduce**
Run the provided example, the "First Window" will be on top, but should not. It should be the "Second Window" and the Dialog that it opens.

**HelloFx.java**

    import javafx.application.Application;
    import javafx.scene.Scene;
    import javafx.scene.control.ButtonType;
    import javafx.scene.control.Dialog;
    import javafx.scene.control.Label;
    import javafx.stage.Modality;
    import javafx.stage.Stage;
    import javafx.stage.Window;
    
    public class HelloFx extends Application {
        @Override
        public void start(Stage primaryStage) {
            
            Scene scene = new Scene(new Label("Primary Stage"), 640, 480);
            primaryStage.setScene(scene);
            primaryStage.show();
            
            new TestStage(primaryStage, "First Window").show();

            TestStage secondStage = new TestStage(primaryStage, "Second Window");
            secondStage.show();
    
            openLastWindow(secondStage);
        }
        
        void openLastWindow(Window owner) {
            Dialog dialog = new Dialog();
            dialog.initOwner(owner);
            dialog.setContentText("Hello world!");
            dialog.setTitle("Last Dialog");
            dialog.initModality(Modality.WINDOW_MODAL);
            dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);

            dialog.showAndWait();
        }
    }
    
    class TestStage extends Stage {
        public TestStage(Window owner, String title) {
            initOwner(owner);
            setTitle(title);
            
            this.setScene(new Scene(new Label("Hello World!"), 400, 400));
        }
    }

**Main.java**

    import javafx.application.Application;
    
    
    public class Main {
        public static void main(String[] args) {
            Application.launch(HelloFx.class, args);
        }
    }

**Comment by tsayao** [comment]
Running the second dialog.showAndWait() inside a Platform.runLater() will work-around the problem (may give a tip where the problem is).

**Comment by tsayao** [comment]
[bugwindowmodal.tar.gz](https://github.com/javafxports/openjdk-jfx/files/2866400/bugwindowmodal.tar.gz)

Full example.

**Comment by tsayao** [comment]
Simplified example of the problem. Just run it. Whe first window will be in front of the second window.




    import javafx.application.Application;
    import javafx.scene.Scene;
    import javafx.scene.control.ButtonType;
    import javafx.scene.control.Dialog;
    import javafx.scene.control.Label;
    import javafx.stage.Modality;
    import javafx.stage.Stage;
    import javafx.stage.Window;
    
    public class HelloFX extends Application {
        
        @Override
        public void start(Stage primaryStage) {
            Scene scene = new Scene(new Label("Primary Stage"), 640, 480);
            primaryStage.setScene(scene);
            primaryStage.show();
            
            new StageOne(primaryStage, "First Window").show();
            StageOne stage = new StageOne(primaryStage, "Second Window");
            stage.show();
            
            openDialogs(stage);
        }
        
        public static void main(String[] args) {
            launch();
        }
        
        void openDialogs(Window owner) {
            openDialog(owner, "Dialog One");
            openDialog(owner, "Dialog Two");
        }
        
        void openDialog(Window owner, String text) {
            Dialog dialog = new Dialog();
            dialog.setContentText(text);
            dialog.initOwner(owner);
            dialog.initModality(Modality.WINDOW_MODAL);
            dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);
            
            dialog.showAndWait();
        }
        
    }
    
    class StageOne extends Stage {
        public StageOne(Window owner, String title) {
            this.initOwner(owner);
            setTitle(title);
            
            this.setScene(new Scene(new Label(title), 400, 400));
        }
    }

**Comment by tsayao** [comment]
I may have found the problem. This seems odd to me:

    GlassWindowEventHandler -> run() -> 
        case WindowEvent.FOCUS_DISABLED:
                stage.handleFocusDisabled();
                break;


    final void handleFocusDisabled() {
        if (activeWindows.isEmpty()) {
            return;
        }
        WindowStage window = activeWindows.get(activeWindows.size() - 1);
        window.setIconified(false);
        window.requestToFront();
        window.requestFocus();
    }


Why handleFocusDisabled() is calling window.requestToFront() on the last window?

**Comment by tsayao** [comment]
Also reported here:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8220272

Providing some additional info. I have added some breakpoints with log (no suspend) and the order of internal window events varies when it shows the problem and when it does not:

**When there is a problem:**

```
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:140)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:140)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
```
**When it works:**

```
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:140)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:140)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
Breakpoint reached at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:69)
```


No changes where made to the program. The behaviour varies.

**Comment by tsayao** [comment]
https://bugs.openjdk.java.net/browse/JDK-8220272
