### ISSUE TITLE
Build error on Win 10

### ISSUE THREAD

**Issue by sonnenhohl** [javafxports/openjdk-jfx#389]
I'm trying to create a build for Windows in 32 bits mode, i have followed the steps on https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX but i'm still having some compiling errors, the tag i'm using is 11+25 and the MSVC version is 14.13.26128 since is the closest to 14.11.25503 available for download.

The error is:

> Task :verifyJava
> Task :base:processVersionInfo UP-TO-DATE
> Task :base:compileJava UP-TO-DATE
> Task :base:processResources NO-SOURCE
> Task :base:classes UP-TO-DATE
> Task :base:jar SKIPPED
> Task :base:assemble UP-TO-DATE
> Task :buildModuleBaseWin UP-TO-DATE
> Task :graphics:generateGrammarSource UP-TO-DATE
> Task :graphics:compileJslcJava UP-TO-DATE
> Task :graphics:compileJava UP-TO-DATE
> Task :graphics:compileDecoraCompilers UP-TO-DATE
> Task :graphics:generateDecoraShaders UP-TO-DATE
> Task :graphics:compileDecoraHLSLShaders UP-TO-DATE
> Task :graphics:processDecoraShaders UP-TO-DATE
> Task :graphics:compilePrismCompilers UP-TO-DATE
> Task :graphics:generatePrismShaders UP-TO-DATE
> Task :graphics:compilePrismHLSLShaders UP-TO-DATE
> Task :graphics:processPrismShaders UP-TO-DATE
> Task :graphics:processShaders UP-TO-DATE
> Task :graphics:compileShadersJava NO-SOURCE
> Task :graphics:processShadersResources NO-SOURCE
> Task :graphics:shadersClasses UP-TO-DATE
> Task :graphics:compileFullJava UP-TO-DATE
> Task :graphics:processResources UP-TO-DATE
> Task :graphics:classes
> Task :graphics:jar SKIPPED
> Task :graphics:compileDecoraNativeShadersWin UP-TO-DATE
> Task :graphics:rcDecoraNativeShadersWin UP-TO-DATE
> Task :graphics:linkDecoraNativeShadersWin UP-TO-DATE
> Task :graphics:nativeDecora UP-TO-DATE
> Task :graphics:ccWinFont UP-TO-DATE
> Task :graphics:rcFont UP-TO-DATE
> Task :graphics:linkWinFont UP-TO-DATE
> Task :graphics:nativeFont UP-TO-DATE
> Task :graphics:ccWinGlass UP-TO-DATE
> Task :graphics:rcGlass UP-TO-DATE
> Task :graphics:linkWinGlass UP-TO-DATE
> Task :graphics:nativeGlass UP-TO-DATE
> Task :graphics:ccWinIio UP-TO-DATE
> Task :graphics:rcIio UP-TO-DATE
> Task :graphics:linkWinIio UP-TO-DATE
> Task :graphics:nativeIio UP-TO-DATE
> Task :graphics:ccWinPrism FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':graphics:ccWinPrism'.
> java.util.concurrent.ExecutionException: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe''

Someone had already faced that problem during a build on Windows?

**Comment by kevinrushforth** [comment]
You might want to run with `gradle --info` to get more information about the failure.

**Comment by sonnenhohl** [comment]
gradle sdk --info

**Comment by sonnenhohl** [comment]
gradle sdk --stackstrace

C:\cygwin64\home\arturs\openjdk-jfx\modules\javafx.graphics\build\gensrc\headers\javafx.graphics\com_sun_prism_j2d_print_J2DPrinterJob.h(15): note: consulte a declara▒▒o de 'Java_com_sun_prism_j2d_print_J2DPrinterJob_getAlwaysOnTop'
NativePiscesRasterizer.c
Helpers.c
SwingInterop.c
Curve.c
Renderer.c
Stroker.c
> Task :graphics:ccWinPrism FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':graphics:ccWinPrism'.
> java.util.concurrent.ExecutionException: org.gradle.process.internal.ExecException: Process 'command 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX86/x86/cl.exe'' finished with non-zero exit value 2

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':graphics:ccWinPrism'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: org.gradle.process.internal.ExecException: Process 'command 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX86/x86/cl.exe'' finished with non-zero exit value 2
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 30 more
Caused by: java.util.concurrent.ExecutionException: org.gradle.process.internal.ExecException: Process 'command 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX86/x86/cl.exe'' finished with non-zero exit value 2
        at java_util_concurrent_Future$get.call(Unknown Source)
        at NativeCompileTask$_compile_closure6.doCall(NativeCompileTask.groovy:161)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at NativeCompileTask.compile(NativeCompileTask.groovy:161)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 43 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX86/x86/cl.exe'' finished with non-zero exit value 2
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:198)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1097)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1092)
        at org.gradle.api.Project$exec$9.call(Unknown Source)
        at CCTask.doCompile(CCTask.groovy:52)
        at jdk.internal.reflect.GeneratedMethodAccessor316.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at NativeCompileTask.this$dist$invoke$3(NativeCompileTask.groovy)
        at NativeCompileTask$1.methodMissing(NativeCompileTask.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at NativeCompileTask$1.run(NativeCompileTask.groovy:150)


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
31 actionable tasks: 3 executed, 28 up-to-date

**Comment by kevinrushforth** [comment]
I see the following error in your log:

> ```
> C:\cygwin64\home\arturs\openjdk-jfx\modules\javafx.graphics\src\main\native-prism\PrismPrint.c(35): error C2373: 'Java_com_sun_prism_j2d_print_J2DPrinterJob_getAlwaysOnTop': redefini▒▒o; modificadores de tipo diferentes
> ```

This is due to:

[JDK-8209791](https://bugs.openjdk.java.net/browse/JDK-8209791): OpenJFX build fails in PrismPrint.c due to missing JNICALL

Which is present in JavaFX 11, but fixed in 11.0.2. Since 11.0.2 includes security fixes and other critical bug fixes, you should build from the 11.0.2+1 tag (or from the tip of 11-dev/rt).
