### ISSUE TITLE
NPE in javafx.graphics/javafx.stage.Window$TKBoundsConfigurator.apply (JDK-8221987)

### ISSUE THREAD

**Issue by christianheilmann** [javafxports/openjdk-jfx#408]
In "javafx.graphics/javafx.stage.Window$TKBoundsConfigurator.apply(...)" is missing the check that the peer is Null for the call "peer.setBounds(...);"
I run in situations where the peer is Null.

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.graphics/javafx.stage.Window$TKBoundsConfigurator.apply(Window.java:1550)
	at javafx.graphics/javafx.stage.Window$TKBoundsConfigurator.pulse(Window.java:1559)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:435)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:562)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:542)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:535)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:341)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by christianheilmann** [comment]
Bug Report is submitted to Oracle Bug Database under internal review ID : 9059794. I will include the bug id when they posted the bug.

**Comment by kevinrushforth** [comment]
https://bugs.openjdk.java.net/browse/JDK-8221987
