### ISSUE TITLE
Fixing JDK-8186553: NPE in TableViewBaseBehavior

### ISSUE THREAD

**Issue by ndm13** [javafxports/openjdk-jfx#436]
https://bugs.openjdk.java.net/browse/JDK-8186553

Encountered this today in 11.0.1-ea+1.  Trivial to reproduce: create an empty editable TableView and press enter while it's focused.  The `activate` method will be called, which will try to get the column of a dummy cell and throw an NPE.

Looks like the same issue is in all current branches:
https://github.com/javafxports/openjdk-jfx/blob/jfx-11/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TableViewBehaviorBase.java#L890
https://github.com/javafxports/openjdk-jfx/blob/jfx-12/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TableViewBehaviorBase.java#L896
https://github.com/javafxports/openjdk-jfx/blob/develop/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TableViewBehaviorBase.java#L896
https://github.com/javafxports/openjdk-jfx/blob/master/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TableViewBehaviorBase.java#L896

Minimal example:
```java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.stage.Stage;


public class OJFXTableView extends Application{
	@Override
	public void start(Stage stage){
		TableView<Object> table = new TableView<>();
		table.getColumns().add(new TableColumn<Object,String>("Column 1"));
		table.setEditable(true);
		stage.setScene(new Scene(table));
		table.requestFocus();
		stage.show();
	}

	public static void main(String[] args){
		launch(args);
	}
}
```

Stacktrace (after pressing Enter):
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.controls/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.activate(TableViewBehaviorBase.java:890)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
	at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kevinrushforth** [comment]
If you would like to provide a fix for this issue, please see [CONTRIBUTING.md](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/CONTRIBUTING.md) for how to proceed.

**Comment by ndm13** [comment]
Possibly when I have some free time outside of work, but not incredibly likely as I have several projects at the moment.  If it's not taken up in a couple weeks I might go through the necessary hoops if I'm not as busy then.  I'm also not really acquainted with the procedures around here, and I'm not sure how to submit a fix for every active branch at once, if that's even something that's possible.

All that would be required would be a null check of the column property before the linked lines.

**Comment by ndm13** [comment]
Upon further inspection, I feel that my proposed null check might be a stopgap.  The same NPE behavior happens when editing rows: that is, when `getFocusedCell()` returns row i, column null and i > 0.  I'm not entirely certain what the "expected behavior" for this scenario is.

Personally, I would choose to go through each cell in the row and continue with the first one with editing enabled for the cell.  This would prevent "unresponsive" behavior when the row is selected and the first column isn't editable.

**Comment by ndm13** [comment]
My naive solution, having only glanced over the code would be to replace:
```java
		boolean isEditable = isControlEditable() && cell.getTableColumn().isEditable();

		// edit this row also
		if (isEditable && cell.getRow() >= 0) {
			editCell(cell.getRow(), cell.getTableColumn());
			e.consume();
		}
```
with:
```java
		if(isControlEditable() && cell != null && cell.getRow() >= 0){
			TableColumnBase column = cell.getTableColumn();
			if(column == null){
				// Determine first editable column
				for(int i = 0; (column = getVisibleLeafColumn(i)) != null; i++){
					if(column.isEditable()){
						break;
					}
				}
			}
			if(column != null && column.isEditable()){
				editCell(cell.getRow(), column);
				e.consume();
			}
		}
```

This is all shadow stabbing, but might be a good start for someone.

**Comment by Adi-18** [comment]
Is there any solution for this? I run into that problem in my project. JDK 11.0.4
