### ISSUE TITLE
Crash in Quantum Renderer

### ISSUE THREAD

**Issue by SebKister** [javafxports/openjdk-jfx#502]
This issue concerns an application in production ( using Corretto jdk11.0.3 +OpenJFX 12.0.1 ) on Windows 10, on other platform the issue is not present.

The application displays custom satellite and drone generated maps.
The texture for those maps are displayed in the UI using that structure: 
Pane<-Group<-ImageView-<Image
The user can zoom and pan the map.

Once a certain threshold of texture is loaded, randomly during zooming or panning the following error occurs:

java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:112)
	at javafx.graphics/com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:121)
	at javafx.graphics/com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:104)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:142)
	at javafx.graphics/com.sun.prism.impl.shape.MaskData.uploadToTexture(MaskData.java:67)
	at javafx.graphics/com.sun.prism.impl.ps.CachingShapeRepState$MaskCache.get(CachingShapeRep.java:317)
	at javafx.graphics/com.sun.prism.impl.ps.CachingShapeRepState.render(CachingShapeRep.java:533)
	at javafx.graphics/com.sun.prism.impl.ps.CachingShapeRep.draw(CachingShapeRep.java:113)
	at javafx.graphics/com.sun.javafx.sg.prism.NGShape.renderContent2D(NGShape.java:293)
	at javafx.graphics/com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:321)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:112)
	at javafx.graphics/com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:121)
	at javafx.graphics/com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:104)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:753)
	at javafx.graphics/com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:146)
	at javafx.graphics/com.sun.prism.impl.BaseGraphics.<init>(BaseGraphics.java:107)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.<init>(BaseShaderGraphics.java:86)
	at javafx.graphics/com.sun.prism.d3d.D3DGraphics.<init>(D3DGraphics.java:42)
	at javafx.graphics/com.sun.prism.d3d.D3DGraphics.create(D3DGraphics.java:65)
	at javafx.graphics/com.sun.prism.d3d.D3DSwapChain.createGraphics(D3DSwapChain.java:134)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
.
.
.

The last NullPointer Exception repeats in a loop and the app GUI is no longer updated.

Any idea on a fix or workaround ?

Thanks!

**Comment by nlisker** [comment]
Without example code it's going to be impossible to say. Could be that the resource was disposed. Also, what is a "threshold of texture"?

**Comment by SebKister** [comment]
I understand very well that without code that will be difficult to diagnose. 
I tried to create a minimalistic example reproducing the bug but haven't been able to do so.
What I call threshold of texture is simply the fact that with 60Mo of texture loaded as TIFF file all goes well, once we get over 80Mo it starts bugging with near certainty within 2min of UI interaction.
