### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory

### ISSUE THREAD

**Issue by mrlimbic** [javafxports/openjdk-jfx#540]
I just tried the zulu build of openjdk with javafx (V8) on Mac OS.

The host services implementation appears to be missing. So showDocument etc wont work.

Is this an openjfx issue on mac or something specific to zulu build?

java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.javafx.application.HostServicesDelegate.lambda$getInstance$0(HostServicesDelegate.java:52)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.HostServicesDelegate.getInstance(HostServicesDelegate.java:45)
	at javafx.application.HostServices.<init>(HostServices.java:52)
	at javafx.application.Application.getHostServices(Application.java:334)
	at net.vordio.ui.VordioApp.start(VordioApp.java:21)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by kevinrushforth** [comment]
This GitHub project is for developing openjfx 11+

Note that openjfx 8u-dev is not maintained as indicated in [this message](https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-January/023039.html).

**Comment by renatoathaydes** [comment]
This problem seems to be affecting not only Azul's distribution, but also the [BellSoft one](https://bell-sw.com/). The fact that JavaFX 8 is no longer maintained is not clear in either the Azul or BellSoft's websites, which still show the downloads including JavaFX prominent. 

@kevinrushforth can you confirm that no other company has stepped up to maintain openjfx 8u-dev?

**Comment by kevinrushforth** [comment]
Correct. There is no maintainer for openjfx 8u-dev.

**Comment by mrlimbic** [comment]
Luckily in this case the app only uses .openDocument from HostServices, so it is easy to work around by natively calling "open" on Mac OS.
