### ISSUE TITLE
WritableImage update fails for empty region

### ISSUE THREAD

**Issue by mipastgt** [javafxports/openjdk-jfx#567]
The newly introduced WritableImages, which are backed by a java.nio.Buffer,
fail to update with an exception when the callback returns an empty Rectangle2D.

```java
java.lang.IllegalArgumentException: srcw (0) and srch (0) must be > 0
	at com.sun.prism.impl.BaseTexture.checkUpdateParams(BaseTexture.java:354)
	at com.sun.prism.es2.ES2Texture.update(ES2Texture.java:640)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(BaseResourceFactory.java:232)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(BaseResourceFactory.java:156)
	at com.sun.javafx.sg.prism.NGImageView.renderContent(NGImageView.java:121)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGImageView.doRender(NGImageView.java:103)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:321)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

According to the documentation the update of the buffer should happen inside the callback
of the updateBuffer method of the PixelBuffer. The returned Rectangle2D is supposed to
indicate which part of the image has become dirty. In practice it may well turn out that
no pixels have changed during the update and it is thus just natural to indicate this
by returning an empty Rectangle2D but obviously the implementation does not handle this
case appropriately. For performance reasons this case should actually be filtered out very
early in the processing pipeline because in this case no further processing is required.

I have attached a test program which links an AWT BufferedImage via an IntBuffer to a
JavaFX WritableImage so that I can draw directly into the BufferedImage via its Graphics2D
context and the result is then displayed via the linked JavaFX image.

The program has three buttons. The first one indicates a full update,
the second one a partial update and the third one an empty update. The third one
crashes for the above mentioned reason which should not be the case.

[Archiv.zip](https://github.com/javafxports/openjdk-jfx/files/3515403/Archiv.zip)

**Comment by mipastgt** [comment]
Reported to JBS with internal review ID : 9061979

**Comment by mipastgt** [comment]
Reference to JBS: https://bugs.openjdk.java.net/browse/JDK-8229890
