### ISSUE TITLE
Leak in MenuItem with accelerator and NPE in MenuButtonSkinBase

### ISSUE THREAD

**Issue by dev-sce** [javafxports/openjdk-jfx#578]
It seems to me that I found two bugs using the same test.

1- Even if a MenuItem with an accelerator is removed from a MenuBar, the MenuItem is not eligible for garbage collection.

2- If we update a MenuBar while displayed, the following exception is thrown:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Step to reproduce 1 :**

- Run the following code :
```
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.CheckMenuItem;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyCodeCombination;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class AcceleratorsLeak extends Application {
	private static int cpt;
	private MenuBar menuBar;

	public static void main(String[] args) {
		System.out.println(System.getProperty("java.version"));
		repeatGC(1000);
		launch(args);
	}

	private static void repeatGC(int p) {
		new Thread(() -> {
			while (true) {
				try {
					Thread.sleep(p);
				} catch (InterruptedException e1) {
					e1.printStackTrace();
				}
				System.out.println("gc");
				System.gc();
			}
		}).start();
	}

	@Override
	public void start(Stage primaryStage) throws Exception {
		StackPane renderPane = new StackPane();
		menuBar = new MenuBar();
		updateMenuBar();
		VBox vbox = new VBox(menuBar, renderPane);
		Scene scene = new Scene(vbox, 640, 480);
		primaryStage.setScene(scene);
		primaryStage.show();
		
		new Thread(() -> {
			while (true) {
				try {
					Thread.sleep(2000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				Platform.runLater(() -> updateMenuBar());
			}
		}).start();
	}

	private void updateMenuBar() {
		menuBar.getMenus().clear();
		menuBar.getMenus().add(getMenu());
	}

	private Menu getMenu() {
		Menu viewMenu = new Menu("View");
		String name = "Menu " + Integer.toString(cpt);
		MenuItem menuitem = new MenuItem(name) {
			@SuppressWarnings("deprecation")
			@Override
			protected void finalize() throws Throwable {
				System.out.println(name + " destroyed");
				super.finalize();
			}
		};
		menuitem.setAccelerator(new KeyCodeCombination(cpt == 0 ? KeyCode.A : KeyCode.B)); // If it's the same KeyCode, it's work
		System.out.println(name + " created");
		viewMenu.getItems().add(menuitem);
		cpt++;
		return viewMenu;
	}
}
```
- Wait several seconds 
- The Menu 1 is never destroyed (The text Menu 0 destroyed never appears). If we change the code to set the same KeyCode to the new MenuItem, it's works.

**Step to reproduce 2 :**
- Run the same code
- Click on the menu "View"
- Wait one second
- The NPE appears

**Actual behavior 1 :**
- The Menuitem is not garbage collected

**Actual behavior 2 :**
- A NPE appears

**Expected behavior 1 :**
- The Menuitem is garbage collected

**Expected behavior 2 :**
- No NPE

Reproduced on Windows 10 and Linux Mint

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com).

If you are interested in contributing a fix for this issue, please see [CONTRIBUTING.md](https://github.com/openjdk/jfx/blob/master/CONTRIBUTING.md) in the official [openjdk/jfx](https://github.com/openjdk/jfx) GutHub repo.
