### ISSUE TITLE
JavaFX error at run time, and no error inside of IntelliJ and saw teacher run same exact code with no issues in video

### ISSUE THREAD

**Issue by aortax** [javafxports/openjdk-jfx#639]
Does anyone know how to fix this error in javafx?
I am using IntelliJ and using code provided by my teacher.
This is my POM.XML 

I have tried changing the version to 14, but that doesn't help.   I have also added it to library in IntelliJ manually, and then doing what was mentioned by another user in a similar github thread.

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.psuedo.login.it</groupId>
    <artifactId>W01.Login</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>11</version>
        </dependency>
    </dependencies>


    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.fxml</include>
                </includes>
            </resource>
        </resources>
    </build>


</project>
```

This is my LoginMain.java

```package com.psuedo.login.it;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class LoginMain extends Application
{
    public static void main(String[] args)
    {
        launch(args);

    }

    @Override
    public void start(Stage stage) throws Exception
    {
        Parent root = FXMLLoader
                .load(getClass()
                        .getResource("LoginView.fxml"));

        Scene scene = new Scene(root);

        stage.setTitle("Login Screen");
        stage.setScene(scene);
        stage.show();


    }
}
```

This is my LoginController.class 
```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.psuedo.login.it;

public class LoginController {
    public LoginController() {
    }
}
```

This is my LoginController.Java

```
package com.psuedo.login.it;
public class LoginController {
}
```

This is my LoginView.fxml

```
<?xml version="1.0" encoding="UTF-8"?>

<?import java.lang.*?>
<?import java.util.*?>
<?import javafx.scene.*?>
<?import javafx.scene.control.*?>
<?import javafx.scene.layout.*?>

<AnchorPane xmlns="http://javafx.com/javafx"
            xmlns:fx="http://javafx.com/fxml"
            fx:controller="com.psuedo.login.it.LoginController"
            prefHeight="400.0" prefWidth="600.0">

</AnchorPane>
```

I have tried everything. I have hardcoded Path to fxml in IntelliJ, I have added it as a library to the project, and neither work. I don't get what else I can do in this situation. The error is below.

```
C:\Development\jdk-14.0.2\bin\java.exe --module-path C:/Development/javafx-sdk-14.0.2.1/lib --add-modules=javafx.controls,javafx.fxml --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.4\lib\idea_rt.jar=50342:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.4\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\huzaifa\IdeaProjects\W01.Login\target\classes;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-controls\14\javafx-controls-14.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-controls\14\javafx-controls-14-win.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-graphics\14\javafx-graphics-14.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-graphics\14\javafx-graphics-14-win.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-base\14\javafx-base-14.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-base\14\javafx-base-14-win.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-fxml\14\javafx-fxml-14.jar;C:\Users\huzaifa\.m2\repository\org\openjfx\javafx-fxml\14\javafx-fxml-14-win.jar com.psuedo.login.it.LoginMain
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:832)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	... 5 more

Process finished with exit code 1


```

**Comment by kevinrushforth** [comment]
This issue tracker is not active. I suggest you ask your question on a forum like StackOverflow.
